import React, {useCallback, useEffect, useState} from "react";

import clpFfiJsModuleInit from "clp-ffi-js";
import PropTypes from "prop-types";
import {Eye, Floppy, Pencil, Trash} from "react-bootstrap-icons";
import {useDispatch} from "react-redux";
import {useModalManager} from "ui-layout-manager-dev";

import {useDalEngine} from "../../../Providers/GlobalProviders";
import {setSelectedTraceIdThunk} from "../../../Store/appThunk";
import {deleteTraceThunk} from "../../../Store/appThunk";
import {useTraces} from "../../../Store/useAppSelection";
import {AddTraceName} from "../../Modals/AddTraceName";
import {ShowTraceLog} from "../../Modals/ShowTraceLog";

import "./DebuggingToolBar.scss";

DebuggingToolBar.propTypes = {
    close: PropTypes.func.isRequired,
    args: PropTypes.object.isRequired,
};

/**
 * Debugging Tool Bar component.
 * @return {JSX.Element}
 */
export function DebuggingToolBar () {
    const {engine} = useDalEngine();
    const {openModal} = useModalManager();
    const dispatch = useDispatch();
    const traces = useTraces();
    const [selectedTrace, setSelectedTrace] = useState(null);
    const [traceType, setTraceType] = useState("design");
    const [filteredTraces, setFilteredTraces] = useState([]);

    useEffect(() => {
        if (traces && traceType) {
            const filtered = Object.values(traces).filter(
                (trace) => trace.type === traceType
            );
            console.log(filtered);
            setFilteredTraces(filtered);
        }
    }, [traces, traceType]);

    const saveDesign = useCallback(() => {
        if (engine) {
            engine.save();
            dispatch(setStatusMsg("Saving design..."));
        }
    }, [engine, dispatch]);

    useEffect(() => {
        if (filteredTraces && filteredTraces.length > 0) {
            dispatch(setSelectedTraceIdThunk(filteredTraces[0].uid));
            setSelectedTrace(filteredTraces[0].uid);
        } else {
            dispatch(setSelectedTraceIdThunk(null));
        }
    }, [filteredTraces]);

    useEffect(() => {
        if (selectedTrace) {
            console.log("Selected new trace:", selectedTrace);
            dispatch(setSelectedTraceIdThunk(selectedTrace));
        }
    }, [selectedTrace, dispatch]);

    const setTraceName = useCallback(() => {
        if (selectedTrace) {
            openModal({
                title: "Set Trace Name",
                args: {
                    trace: selectedTrace,
                },
                render: ({close, args}) => {
                    return <AddTraceName close={close} args={args} />;
                },
            });
        }
    }, [selectedTrace, traces, openModal]);

    const deleteTrace = (e) => {
        e.stopPropagation();
        if (selectedTrace) {
            dispatch(deleteTraceThunk(selectedTrace));
        } else {
            console.warn("Trace does not have a valid UID:", selectedTrace);
        }
    };

    const openTraceInEditor = useCallback(async (e) => {
        e.stopPropagation();
        e.preventDefault();
        if (!selectedTrace) {
            return;
        }

        const t = Object.values(traces).find((t) => t.uid === selectedTrace);
        if (!t) return;
        const traceData = t?.trace;

        // TODO: This should be in a worker, but I'm doing it here for now.
        const Module = await clpFfiJsModuleInit();
        const decoder = new Module.ClpStreamReader(traceData, {
            timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
            logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
        );
        const log = decoder.decodeRange(0, decoder.deserializeStream(), false);
        const logContent = log.map((entry) => {
            return JSON.stringify(JSON.parse(entry[0])["user-generated"], null, 2);
        }).join("\n");

        openModal({
            title: "Selected Trace Log",
            args: {
                "trace": logContent,
            },
            render: ({close, args}) => {
                return <ShowTraceLog close={close} args={args} />;
            },
        });
    }, [selectedTrace, traces]);

    return (
        <div className="debuggingToolBar">
            <div className="debuggingToolBarLeft">
                <span className="debuggingToolBarLabel">Debug:</span>
                <span className="debuggingToolBarSelect" >
                    <select
                        value={traceType}
                        onChange={(e) => setTraceType(e.target.value)}>
                        <option key={"semantic"} value={"design"}>Semantic Model</option>
                        <option key={"implementation"} value={"implementation"}>
                            Implementation
                        </option>
                    </select>
                </span>
                <span className="debuggingToolBarLabel">Select Trace:</span>
                <span className="debuggingToolBarSelect" >
                    <select
                        value={selectedTrace}
                        onChange={(e) => setSelectedTrace(e.target.value)}>
                        {filteredTraces.map((trace) => (
                            <option key={trace.uid} value={trace.uid}>{
                                (trace?.name ? trace.name : trace.timestamp)
                            }</option>
                        ))}
                    </select>
                </span>
            </div>
            <div className="debuggingToolBarRight">
                <span className="debuggingToolBarButton" onClick={setTraceName}>
                    <Pencil
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span>Set Trace Name</span>
                </span>
                <span className="debuggingToolBarButton" onClick={openTraceInEditor}>
                    <Eye
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span>View Raw Trace</span>
                </span>
                <span className="debuggingToolBarButton" onClick={deleteTrace}>
                    <Trash
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span>Delete Trace</span>
                </span>
                <span className="debuggingToolBarButton" onClick={saveDesign}>
                    <Floppy
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span>Save</span>
                </span>
            </div>
        </div>
    );
}
