import React, {useCallback, useEffect, useState} from "react";

import clpFfiJsModuleInit from "clp-ffi-js";
import PropTypes from "prop-types";
import {BoxArrowInUpRight, Bug, CircleFill, Trash} from "react-bootstrap-icons";
import {useDispatch} from "react-redux";
import {useModalManager} from "ui-layout-manager-dev";

import {setSelectedTraceIdThunk} from "../../../Store/appThunk";
import {deleteTraceThunk} from "../../../Store/appThunk";
import {useSelectedTraceId} from "../../../Store/useAppSelection";
import {ShowTraceLog} from "../../Modals/ShowTraceLog";

import "./TraceSelectRow.scss";

TraceSelectRow.propTypes = {
    trace: PropTypes.object.isRequired,
};

/**
 * Trace select row component.
 * @param {Object} props
 * @param {Object} props.trace - The trace to display in this row.
 * @return {JSX.Element}
 */
export function TraceSelectRow ({trace}) {
    const dispatch = useDispatch();
    const [dateRenered, setDateRendered] = useState("");
    const selectedTraceId = useSelectedTraceId();
    const {openModal} = useModalManager();

    useEffect(() => {
        if (trace?.name) {
            setDateRendered(trace.name);
        } else if (trace?.timestamp) {
            const date = new Date(trace.timestamp);
            const formatted = date.getFullYear() + "-" +
                String(date.getMonth() + 1).padStart(2, "0") + "-" +
                String(date.getDate()).padStart(2, "0") + " " +
                String(date.getHours()).padStart(2, "0") + ":" +
                String(date.getMinutes()).padStart(2, "0") + ":" +
                String(date.getSeconds()).padStart(2, "0");
            setDateRendered(formatted);
        }
    }, [trace]);

    const selectTrace = (e) => {
        e.stopPropagation();
        if (trace?.uid !== selectedTraceId) {
            dispatch(setSelectedTraceIdThunk(trace.uid));
        } else if (trace?.uid === selectedTraceId) {
            dispatch(setSelectedTraceIdThunk(null));
        } else {
            console.warn("Trace does not have a valid UID:", trace);
        }
    };

    const deleteTrace = (e) => {
        e.stopPropagation();
        if (trace?.uid) {
            dispatch(deleteTraceThunk(trace.uid));
        } else {
            console.warn("Trace does not have a valid UID:", trace);
        }
    };

    const openTraceInEditor = useCallback(async (e) => {
        e.stopPropagation();
        e.preventDefault();
        if (!trace || !trace.trace) {
            console.warn("Trace does not have valid data:", trace);
            return;
        }

        // TODO: This should be in a worker, but I'm doing it here for now.
        const Module = await clpFfiJsModuleInit();
        const data = (trace?.trace?.data) ? trace.trace.data : trace.trace;
        const decoder = new Module.ClpStreamReader(data, {
            timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
            logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
        );
        const log = decoder.decodeRange(0, decoder.deserializeStream(), false);
        const logContent = log.map((entry) => {
            return JSON.stringify(JSON.parse(entry[0])["user-generated"], null, 2);
        }).join("\n");

        openModal({
            title: "Selected Trace Log",
            args: {
                "trace": logContent,
            },
            render: ({close, args}) => {
                return <ShowTraceLog close={close} args={args} />;
            },
        });
    }, [trace]);

    const openDebugResult = useCallback(() => {
        console.log(trace);
        const data = trace.debugger._executableSemanticModelOutputs;
        const str = JSON.stringify(data, null, 2);
        openModal({
            title: "Automated Debug Results",
            args: {
                "trace": str,
            },
            render: ({close, args}) => {
                return <ShowTraceLog close={close} args={args} />;
            },
        });
    }, [trace]);

    return (
        <div className="trace-select-row-container"
            onClick={selectTrace}>
            <div className="selected-icon-container">
                {selectedTraceId === trace.uid && <CircleFill size={10} color="#007acc" />}
            </div>
            <div className="date-container">
                {dateRenered}
            </div>
            <div className="trash-icon-container">
                <Trash title="Delete Trace" size={14} color="grey" onClick={deleteTrace} />
            </div>
            <div className="trash-icon-container">
                <Bug
                    title="Open Debug Results in Editor"
                    size={14} color="grey"
                    onClick={openDebugResult} />
            </div>
            <div className="trash-icon-container">
                <BoxArrowInUpRight
                    title="Open Trace in Editor"
                    size={14} color="grey"
                    onClick={openTraceInEditor} />
            </div>
        </div>
    );
}
